name: flutterhub
description: A new Flutter project.

version: 1.0.0+9

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.0.0
  cached_network_image: ^3.2.1
  chopper: ^8.0.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.3
  filesize: ^2.0.1
  flex_color_scheme: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6
  flutter_secure_storage: ^9.0.0
  flutter_web_auth: ^0.5.0
  font_awesome_flutter: ^10.0.0
  formz: ^0.7.0
  freezed_annotation:
  get_it: ^7.0.0
  google_fonts: ^6.0.0
  intl: any
  json_annotation: ^4.8.1
  logging: ^1.0.0
  mobx: ^2.0.0
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.0
  timeago: ^3.0.0
  url_launcher: ^6.0.0

flutter_intl:
  main_locale: en_US
  enabled: true

dev_dependencies:
  build_runner: ^2.4.0 # dart run build_runner build --delete-conflicting-outputs
  chopper_generator: any
  flutter_gen: ^5.0.0
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.0 # flutter pub run flutter_native_splash:create
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  icons_launcher: ^2.0.0 # flutter pub run icons_launcher:create
  json_serializable: ^6.0.0
  mobx_codegen:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#131d25"
  image: assets/images/app_logo.png

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon_border.png"
  image_path_ios: 'assets/images/app_icon.png'
  adaptive_icon_background: '#01579B'
  adaptive_icon_foreground: 'assets/images/app_icon_adaptive.png'
  adaptive_icon_round: 'assets/images/app_icon_round.png'
